"""add restaurant_pizzas association table

Revision ID: 335ae5f20ff4
Revises: ecc846cd7edd
Create Date: 2024-04-09 04:39:56.484492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335ae5f20ff4'
down_revision = 'ecc846cd7edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_pizzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('pizza_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_pizzas')
    # ### end Alembic commands ###
