"""add RestaurantPizza association model

Revision ID: ecc846cd7edd
Revises: bab66b8a3abd
Create Date: 2024-04-09 04:27:58.682004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc846cd7edd'
down_revision = 'bab66b8a3abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RestaurantPizza')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RestaurantPizza',
    sa.Column('restaurant_id', sa.INTEGER(), nullable=False),
    sa.Column('pizza_id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.CheckConstraint('price >= 1 AND price <= 30', name='check_price_range'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id', 'pizza_id')
    )
    # ### end Alembic commands ###
